# Generated by Django 4.2.13 on 2024-11-05 13:46

import core.utils
import core.validators.file_max_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doenca', '0002_remove_doenca_sinais_clinicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doenca',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.save_file_to, validators=[core.validators.file_max_size.FileMaxSizeValidator()], verbose_name='Imagem'),
        ),
    ]
